---
- summary: |
    Тестирование смены языка на "Russian".
  requirement: |
    При смене языка должен отображться используемый язык в полной мере и с максимально возможным покрытием. 
  prerequisites: |
    Открыта страница сайта.
  test-data: |
    Тестовые данные
    https://hexlet-products-store.vercel.app/ 
  steps:
    Нажимаем кнопку "Language".
    Нажимаем на "Russian", во всплывающем списке.
  expected-result: |
    Отображается сайт с основным языком "Russian".

- summary: |
    Тестирование сортировщика по цене.
  requirement: |
    Сортировка по цене работает корректно.
  prerequisites:
    Открыта страница сайта.
  test-data: |
    Тестовые данные 
    https://hexlet-products-store.vercel.app/ 
  steps:
    Проводим тестирование граничных значений.
  expected-result: |
    Сортировка по цене работает корректно.

- summary: |
    Тестирование поисковой стоки на сайте.
  requirement: |
    Поисковая строка соответствует требованиям и работает корректно.
  prerequisites:
    Открыта страница сайта.
  test-data: |
    Тестовые данные 
    https://hexlet-products-store.vercel.app/ 
  steps:
    Проводим тестирование поисковой строки.
  expected-result: |
    Поисковая строка соответствует требованиям и работает корректно.
