---
- summary: |
    Тестирование смены языка на "Russian".
  status: fall

- summary: |
    Тестирование сортировщика по цене.
  status: fall

- summary: |
    Тестирование поисковой стоки на сайте.
  status: pass

- summary: |
    Тестирование функционала корзины товаров.
  status: fall
  
- summary: |
    Тестирование визуальной составляющей.
  status: fall
